### ISSUE TITLE
Player can clip through walls with the gold quad

### ISSUE THREAD

**Issue by PolariTOON** [SuperBearAdventure/tracker#1]
**Bug description:**

The player is able to go out of bounds by clipping through wall with the gold quad at high speed in the Beemothep Desert.
The lower the framerate is, the more likely it is to happen. It can still happen in 60fps, though.

**Expected behavior:**

The player should collide with the wall.

**Do you think this a regression?**

- [ ] Unknown
- [x] Yes, I think it worked in a previous version of the game
- [ ] No, I do not think so

**Screen records or screenshots:**

Here the links: https://user-images.githubusercontent.com/36267812/124971883-0742d200-e02a-11eb-9434-d8b44e7c842c.mp4 with the framerate set to 15fps

**Platform:**

- [ ] Unknown
- [x] Android
- [ ] iOS

**Game version:**

1.9.8

**Has this been reported on Discord before?**

- [ ] Unknown
- [x] Yes, here the link: https://discord.com/channels/398832325728796672/490823920786866197/853007011604201522
- [ ] Yes, I think so, but I do not have a link
- [ ] No, I do not think so

**Additional context:**

None

**Comment by Earthkwak-Games** [comment]
Added 10m wide box colliders to replace the wall's mesh collider. Collisions is now handled correctly at high speeds.
