### ISSUE TITLE
Ledge grabbing in a teleporter makes the player wrong warp

### ISSUE THREAD

**Issue by PolariTOON** [SuperBearAdventure/tracker#13]
**Bug description:**

Grabbing an edge while entering a trigger teleports the player to the wrong position, potentially out of bounds. This has been reported several times by players triggering this behavior unintentionally, especially in the current hive. However, this can actually happen in any teleporter that has an edge near it.

Not sure this is a new bug, but this was likely revealed because of the extended ledge grabbing introduced in 1.9.8.

**Expected behavior:**

The player should be teleported to the intended position, whether or not an edge is being grabbed.

**Do you think this a regression?**

- [ ] Unknown
- [x] Yes, I think it worked in a previous version of the game
- [ ] No, I do not think so

**Screen records or screenshots:**

Here the links:
- The common way to trigger the bug in the hive: https://user-images.githubusercontent.com/36267812/126313621-e4bd4859-0e6f-4b45-a8ed-2b6077c43a8b.mp4
- The same place, but triggering a cutscene almost immediately: https://user-images.githubusercontent.com/36267812/126313758-7bf3ca1f-ec71-4d04-b578-d04247c0f400.mp4
- During missions: https://user-images.githubusercontent.com/36267812/126313940-0198c506-7941-4a4d-8c4b-82ccfa3b012f.mp4
- Building an edge with blocks: https://user-images.githubusercontent.com/36267812/126314624-72345b3e-6c4e-41dc-988e-1ff2dffc5960.mp4
- In a chimney: https://user-images.githubusercontent.com/36267812/126543284-b10a9d02-07a3-4738-883f-de23d6d4d001.mp4

**Platform:**

- [ ] Unknown
- [x] Android
- [ ] iOS

**Game version:**

1.9.8

**Has this been reported on Discord before?**

- [ ] Unknown
- [x] Yes, here the link: https://discord.com/channels/398832325728796672/490823920786866197/859126753150500905
- [ ] Yes, I think so, but I do not have a link
- [ ] No, I do not think so

**Additional context:**

None

**Comment by Earthkwak-Games** [comment]
Now the player stops ledge grabbing when touching a teleporter
