### ISSUE TITLE
Camera shot after rescuing Alix can be confusing

### ISSUE THREAD

**Issue by PolariTOON** [SuperBearAdventure/tracker#3]
**Bug description:**

If the player saves Alix while the camera transition for exiting the puzzle is still ongoing, the camera will not go back to the previous position when exiting the rescue menu.
This is confusing, especially for speedrunners, because this is not happening for the other bears and used not to happen for this one too.
Also the cage looks uncentered while the rescue menu is open.

**Expected behavior:**

The same behavior as for the other bears: let the camera go back to its position, or abort the transition when opening the cage.

**Do you think this a regression?**

- [ ] Unknown
- [x] Yes, I think it worked in a previous version of the game
- [ ] No, I do not think so

**Screen records or screenshots:**

Here the links: https://user-images.githubusercontent.com/36267812/124978330-ebdbc500-e031-11eb-86be-215509359598.mp4

**Platform:**

- [ ] Unknown
- [x] Android
- [ ] iOS

**Game version:**

1.9.8

**Has this been reported on Discord before?**

- [ ] Unknown
- [ ] Yes, here the link: not filled in
- [ ] Yes, I think so, but I do not have a link
- [x] No, I do not think so

**Additional context:**

None

**Comment by Earthkwak-Games** [comment]
Smooth transitions from "Fixed Camera Triggers" are now canceled if you start a cutscene (like saving a bear)
