### ISSUE TITLE
Football clip

### ISSUE THREAD

**Issue by Yarocrafter** [SuperBearAdventure/tracker#36]
**Bug description:**

When you keep jumping on any vine and hold forward with football hat equiped, you can randomly clip through the vine. A similar clip can happen with deer king

**Expected behavior:**

Do not clip through

**Do you think this a regression?**

- [x] Unknown
- [ ] Yes, I think it worked in a previous version of the game
- [ ] No, I do not think so

**Screen records or screenshots:**

Here the links: https://discord.com/channels/398832325728796672/490823920786866197/872910061217939477
https://discord.com/channels/398832325728796672/490823920786866197/874492289832091649

**Platform:**

- [ ] Unknown
- [x] Android
- [ ] iOS

**Game version:**

1.9.9

**Has this been reported on Discord before?**

- [ ] Unknown
- [x] Yes, here the link: https://discord.com/channels/398832325728796672/490823920786866197/872910061217939477
https://discord.com/channels/398832325728796672/490823920786866197/874492289832091649
- [ ] Yes, I think so, but I do not have a link
- [ ] No, I do not think so

**Additional context:**

None

**Comment by Earthkwak-Games** [comment]
The football hat no longer spawn balls out of bounds and the balls no longer affect the player upon spawning
