### ISSUE TITLE
Yeti snowballs do not always come from its hand after reviving

### ISSUE THREAD

**Issue by PolariTOON** [SuperBearAdventure/tracker#4]
**Bug description:**

After dying and reviving during the yeti battle, the snowballs the yeti usually throws sometimes appear to come from underground. It may depends on what yeti attack is ongoing when the player is killed.

**Expected behavior:**

The snowballs should come from its hand. This is the current behavior if the player do not die during this battle.

**Do you think this a regression?**

- [ ] Unknown
- [ ] Yes, I think it worked in a previous version of the game
- [x] No, I do not think so

**Screen records or screenshots:**

Here the links: https://user-images.githubusercontent.com/36267812/124986410-df5c6a00-e03b-11eb-9097-a73fbbb99bcb.mp4

**Platform:**

- [ ] Unknown
- [x] Android
- [ ] iOS

**Game version:**

1.9.8

**Has this been reported on Discord before?**

- [ ] Unknown
- [x] Yes, here the link: https://discord.com/channels/398832325728796672/490823920786866197/722783113402384394
- [ ] Yes, I think so, but I do not have a link
- [ ] No, I do not think so

**Additional context:**

This bug was first reported for 1.8.5.1.

**Comment by Earthkwak-Games** [comment]
The yeti code was made in 2017 and was a mess. I cleaned up the code and reworked animations and effects of this boss fight.
