### ISSUE TITLE
Giant house and beta hive do not have skyboxes

### ISSUE THREAD

**Issue by PolariTOON** [SuperBearAdventure/tracker#5]
**Bug description:**

The Giant House and the current Hive apparently do not have a skybox, because they are basically closed levels. However the rendering is undefined when the camera points to out of bounds areas. This is the case when the camera goes iout of bounds (while talking to a NPC, or when the game over menu is open) or when the player goes itself out of bounds. On some devices, this renders as a black box, but on some others, this displays weird patterns from previous frames or other parts of the screen, likely showing uninitialized parts of a framebuffer. In this case, this is confusing for players.

**Expected behavior:**

Always give a texture to the skyboxes, a solid black background should be fine, as this is how it currently renders on some devices.

**Do you think this a regression?**

- [ ] Unknown
- [ ] Yes, I think it worked in a previous version of the game
- [x] No, I do not think so

**Screen records or screenshots:**

Here the links: https://user-images.githubusercontent.com/36267812/124990951-52b4aa80-e041-11eb-8049-845d6a261056.png

**Platform:**

- [ ] Unknown
- [x] Android
- [ ] iOS

**Game version:**

1.9.8

**Has this been reported on Discord before?**

- [ ] Unknown
- [ ] Yes, here the link: not filled in
- [x] Yes, I think so, but I do not have a link
- [ ] No, I do not think so

**Additional context:**

This is a long-standing bug that was reported many times.

**Comment by Earthkwak-Games** [comment]
This is a side effect of the 3D Skybox. It can't be fixed but shouldn't happen unless the player is going out of bounds.
