### ISSUE TITLE
Player animation can go in an unintended state when pressing A and B at the same time in the water

### ISSUE THREAD

**Issue by PolariTOON** [SuperBearAdventure/tracker#6]
**Bug description:**

Doing a frame perfect A + B press (while moving in the water?) makes the player animation get stuck in a state close to the "falling" one.

**Expected behavior:**

Unknown

**Do you think this a regression?**

- [x] Unknown
- [ ] Yes, I think it worked in a previous version of the game
- [ ] No, I do not think so

**Screen records or screenshots:**

Here the links: https://user-images.githubusercontent.com/36267812/124993852-3a468f00-e045-11eb-9932-943e51f4573c.mp4

**Platform:**

- [ ] Unknown
- [x] Android
- [ ] iOS

**Game version:**

1.9.8

**Has this been reported on Discord before?**

- [ ] Unknown
- [x] Yes, here the link: https://discord.com/channels/398832325728796672/490823920786866197/859204502393585705
- [ ] Yes, I think so, but I do not have a link
- [ ] No, I do not think so

**Additional context:**

None

**Comment by Earthkwak-Games** [comment]
The player was jumping and going underwater on the same frame. I added a simple "else" keyword to avoid doing both in the same frame. The new behavior is that the player doesn't jump.
