### ISSUE TITLE
The clavier in the giant house does not emit any sound

### ISSUE THREAD

**Issue by PolariTOON** [SuperBearAdventure/tracker#9]
**Bug description:**

When walking on the clavier in the giant house, no sound effects play. It used to play notes earlier.

**Expected behavior:**

It should play notes, like it used to be.

**Do you think this a regression?**

- [ ] Unknown
- [x] Yes, I think it worked in a previous version of the game
- [ ] No, I do not think so

**Screen records or screenshots:**

Here the links: https://user-images.githubusercontent.com/36267812/125620573-d4806d6a-bbc6-4fe4-90a6-a314973ac475.mp4

**Platform:**

- [ ] Unknown
- [x] Android
- [ ] iOS

**Game version:**

1.9.8

**Has this been reported on Discord before?**

- [ ] Unknown
- [x] Yes, here the link: https://discord.com/channels/398832325728796672/490823920786866197/857218739626835970
- [ ] Yes, I think so, but I do not have a link
- [ ] No, I do not think so

**Additional context:**

I think the regression happened in 1.9.8, when the player physics system was remade.

**Comment by Earthkwak-Games** [comment]
I updated the collision detection to be compatible with the KCC (1.9.8 player physics)
